[".config/zsh/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/tags/0.8.0.tar.gz"
    exact = true
    stripComponents = 1
    include = [ "*/*.zsh", "*/.version", "*/.revision-hash", "*/highlighters/**" ]

[".config/zsh/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/tags/v0.7.1.tar.gz"
    exact = true
    stripComponents = 1
    include = [ "*/*.zsh" ]

[".local/share/nvim/lombok/lombok.jar"]
    type = "file"
    url = "https://projectlombok.org/downloads/lombok.jar"
